!mouse copy and paste on Windows the same on Linux!
fini $ /clear
/prep7

*afun,deg
Pi = acos(-1)
*afun,rad
Pi = acos(-1)

!case sensitive completion
!Pi = ac

!Emacs calc
Pi = 

!! abbrev `p
p

*!completion ESC Tab under Windows!

!dynamic completion
very_long_Variable = 3
vlV = 8
v

!closing of blocks, dynamic variable fontification

I 
!(progn (setq ansys-highlighting-level 1 ansys-dynamic-highlighting-flag nil) (ansys-mode))
!(progn (setq ansys-highlighting-level 2 ansys-dynamic-highlighting-flag t) (ansys-mode))
*if,I,eq,1,then
  c*** otto
*elseif,I,le,10
  /com,help me
*else
  /title,well well
  
!commenting out, code comments M-j
!Marking blocks: C-M-h  

!abbrev `d

d
 
!C-c C-c, C-w copying lines, condensed input, default command
x2 = 1 $ y2 = 1 $ z2 = 1
block,,x2,,y2,,z2
,x2,2*x2,,2*y2,,2*z2
	   
!mouse completion of vglue
vg

/pnum,line,1 $ lplo

!materials & deprecated elements
et,10,solid46

!C-c C-u  copy above 

!meshing, colon loops
lesi,(:)

!bc
!solution 
!post 1 

/eof --- WARNING: /eof crashes the Ansys GUI in interactive mode ---
 

!! switch off menu, tools, scroll-bar
!! Ansys mode help: C-h m, selfdocumenting features
!! online Ansys/Emacs process and debugging environment
!! C-c C-u, C-c C-c,  C-c C-q
!! tail mode of *.err C-c C-e
!! abort file
!! positions -> in bookmarks/registers/clone buffer?
!! C-c @ outline stuff with indirect-buffer
!! image Dired (textual renaming), Calendar
!! shell-, config-mode, emacsclient, terminal-, ssh-support
!! C-S-backspace
