#+TITLE:     ANSYS-Mode Tutorial
#+AUTHOR:    H. Dieter Wilhelm
#+EMAIL:     dieter@duenenhof-wilhelm.de
#+DATE:      2012-06-19 Tue
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:2 num:t toc:t \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
##+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+PROPERTY: tangle yes

* Introduction
** Read the introductory ansys-mode_tutorial.pdf
   or use the online version.  You will learn that
   
  1. ANSYS-Mode is improving your workflow with
  2. Two parts: Run through some documentation then hands-on
  3. Simple download, installation (no admin rights), no configuration
     (for Win64/Lin64, but most things should run anyway)
  4. No costs and practically no license restrictions also for
     commercial use

* APDL viewer
*** Interesting even for pure WB users: true understanding with input files!

*** drag and drop: finite_field60.dat (M-n/p does not work in element numbered eblocks, nblocks!)

*** command-help from menu

*** -start-ansys-help from menu

***  navigation (number blocks in .dat files) C-c {

* APDL hacking
** Code templates
Insert in the file APDL_tutorial.ansys here below this line the skeleton (C-u C-c C-s)  -structural-template

*** type *C-u C-c C-s* or choose the structural template from the ANSYS-Mode menu

#+begin_src ansys  :tangle yes
  ! insert here below this line the skeleton (C-u C-c C-s)  -structural-template
#+end_src

** convenience features? C-c C-v (not with big, 60 MB, files ;-)

!! -copy-above C-c C-u, copy line or marked region C-c C-c

** Commenting, Un-commenting
*** mark some text with the mouse and type *M-;* 
Hint: Marking blocks: *C-M-h*
Selcting paragraphs: *M-h*
!!    selecting blocks C-M-a/b setting mark!

*** mark commented region again an type again *M-;*
*** code comments M-j

** Use the Emacs integrated RPN Calculator
   RPN (Reversed Polish Notation, HP calculators are using this input convention

*** Place the cursor behind the assignment (=) and type *C-x* * *
    to fire up Emacs Calc
#+begin_src  ansys : tangle yes
!! Place the cursor behind the assignment (=) and type C-x * * 
Pi =
#+end_src


!!    mouse selection ->copy to clipboard
!! 0.) mouse selection does not work under Windows mouse-drag-copy-region!
!! mouse copy on Windows the same on Linux only if (setq mouse-drag-copy-region t)


fini $ /clear
/prep7
*afun,deg
Pi = acos(-1)
*afun,rad
Pi = acos(-1)
x = 3.4 !lsk
y = .8	!ach

** Alignment of variable definitions

*** place the cursor on the following paragraph and type C-c a

#+begin_src ansys : tangle yes
!! place the cursor on the following paragraph and type C-c a
x=0.4!laskd
y= 33.0	    ! alskdl
xzv= 9999990.3	    !!
llk = 0.333333333 !bla
al_=  00.40
aslföas = 304
ka= .4	    !salkd
i = 4.		    !as
kasd=.3/0.4
kasd =3./0.4
xxx =asin(3.0)
y = cos(i)
#+end_src

**  completions
    case sensitive
*** place the cursor behind 'ac' and type *M-TAB*
#+begin_src ansys : tangle yes
!! place the cursor behind 'ac' and type *M-TAB*
Pi = ac
#+end_src ansys : tangle yes

** Abbreviations facility

!abbrev `d do i if

d
   `p
#+begin_src ansys : tangle yes
p
#+end_src


** Dynamic completions
!!    M-/, M-x abbrev-mode (list-abbrevs 1) display locally
!!    default (,) commands but most */ can't be "*repeated"
#+begin_src ansys : tangle yes
very_long_Variable = 3
vlV = 8
#+end_src
*** type *M-TAB* repeatedly behind the 'v'
    (*ESC TAB* under Windows)
#+begin_src ansys : tangle yes
v
#+end_src


** Insert pairs of characters
   possibly around a whole word or section
*** type *C-c %*
!!    C-c %,',M-"
#+begin_src  ansys : tangle yes
XX=55
/com,the result of XX is %XX%
#+end_src

** Closing of blocks, dynamic variable fontification

I 
!(progn (setq ansys-highlighting-level 1 ansys-dynamic-highlighting-flag nil) (ansys-mode))
!(progn (setq ansys-highlighting-level 2 ansys-dynamic-highlighting-flag t) (ansys-mode))
***  Ansys symbol completion and emacs expansion C-c ] -- -close-block
#+begin_src  ansys : tangle yes
*if,I,eq,1,then
  c*** otto
*elseif,I,le,10
  /com,help me
*else
  /title,well well
#+end_src
 
!C-c C-c, C-w copying lines, condensed input, default command
x2 = 1 $ y2 = 1 $ z2 = 1
immed,on
block,,x2,,y2,,z2
,x2,2*x2,,2*y2,,2*z2
	   
!mouse completion of vglue
vg

/pnum,line,1 $ lplo

** materials & deprecated elements
#+begin_src  ansys : tangle yes
et,10,solid46
#+end_src

!C-c C-u  copy above 

!meshing, colon loops, repeating
lesi,(:)
*repeat,2

!bc
!solution 
!post 1 

!!    colon loop: e.g.: lfillt,(1:3),(2:4),Rad, lesize,(1:5:2),Esize
!!    _return & _status values
!!    preview C-c C-s (completion), insert skeletons
!!    (alternatively abbrev mode?)

!!    *go not for interactive mode! -> *if *else *endif

*** loading help navigator *C-c C-h*
***   display license status	-license-status *C-c C-l*

#+begin_src  ansys : tangle yes
/eof --- WARNING: /eof crashes the Ansys GUI in interactive mode ---
#+end_src

* Solver interaction and debugging or 'hardcore APDL' (Unix only)


- Switch off menu-, tool- and scroll-bars

***    M-w (copies line)

# !!    Ansys mode help: C-h m, selfdocumenting features
# !!    online Ansys/Emacs process and debugging environment
# !!    interactive C-c C-u, C-c C-c,  C-c C-q
# !!    tail mode of *.err C-c C-e
# !!    abort file
# !!    positions -> in bookmarks/registers/clone buffer?
# !!    C-c @ outline stuff with indirect-buffer
# !!    Dired (textual renaming), speedbar, calendar
# !!    loading time: emacsclient alias "e"
# !!    shell-, config-mode, emacsclient, terminal-, ssh-support
# !!    C-S-backspace, basically the same keyboard shortcuts like bash
# !! switch off menu, tools, scroll-bar
# !! Ansys mode help: C-h m, selfdocumenting features
# !! calc: linear interpolation: a p [[x1,x2,..][y1,y2,...]] x
# !! online Ansys/Emacs process and debugging environment
# !! C-c C-u, C-c C-c,  C-c C-q
# !! tail mode of *.err C-c C-e
# !! abort file
# !! positions -> in bookmarks/registers/clone buffer?
# !! C-c @ outline stuff with indirect-buffer
# !! image Dired (textual renaming), speedbar, calendar
# !! shell-, config-mode, emacsclient, terminal-, ssh-support
# !! C-S-backspace

** Embeded calc

0.416195720427

2 x => 2 x

   
* Last slide, Conclusion/Summary?
Thank you for your time


* Emacs introcuction
!! -- Very brief introduction: Emacs, why not?  Gnu Puplic Licens ->
# !!    Free, working on all current OSs.  All bells and whistle of a
# !!    modern editor (drop file into E), excellent documentation.  Chosen
# !!    because with Vim, Emacs is the best editor of all, but - especially
# !!    on Windows - programmed before Microsoft was even founded.
# !!    Drawbacks of Emacs, not adhering to established user interface
# !!    standards example: e. g. scroll-bar default location on linux on
# !!    the left,

# !!    Splitting windows (no tab concept for buffers)

# !!    TAB, M-TAB keys, C-s, C-c, C-v, C-x, C-y, C-z CUA-mode examples:
# !!    (setq scroll-preserve-screen-position t) (delete-selection-mode t)
# !!    Workaround: use in the beginning mouse and buttons.
   
# !!    convenient pre-configured emacs archive with Ansys mode.


# #+begin_src R :exports both
# # this is a comment, yeah :-)
#  bla <- 3
# bla 
# #+end_src
# #+RESULTS:
# : 3


######################################################################
#+begin_src ansys  :tangle yes
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! this is for Emacs:

!! local variables:
!! mode : ansys
!! end:
#+end_src
