!mouse copy and paste under Windows like under Linux!
fini $ /clear
/prep7

*afun,deg
Pi = acos(-1)
*afun,rad

!completion
!Pi = ac

!Emacs calc
Pi = 
!! interpolation with Emacs calc '[[x1 x2][y1 y2 RET X_value a p

!! abbrev `p
p

*!completion ESC Tab under Windows!

!dynamic completion
very_long_Variable = 3
vlV = 8
v

!closing of blocks, dynamic variable fontification

I 
*if,I,eq,1,then
  c*** otto
*elseif,I,le,10
  /com,help me
*else
  /title,well well
  
!commenting out
!Marking blocks: C-M-h  

!abbrev `d

d
 
!C-c C-c, C-w copying lines, condensed input, default command
x2 = 1 $ y2 = 1 $ z2 = 1
block,,x2,,y2,,z2

!mouse completion
vg

/pnum,line,1 $ lplo

!materials & deprecated elements
et,10,solid46

!C-c C-u  copy above 

!meshing, colon loops
les,()

!bc
!solution 
!post 1 
 

!! switch off menu, tools, scroll-bar
!! Ansys mode help: C-h m, selfdocumenting features
!! online Ansys/Emacs process and debugging environment
!! C-c C-u, C-c C-c,  C-c C-q
!! tail mode of *.err C-c C-e
!! abort file
!! positions -> in bookmarks/registers/clone buffer?
!! C-c @ outline stuff with indirect-buffer
!! image Dired (textual renaming), Calendar
!! shell-, config-mode, emacsclient, terminal-, ssh-support
!! C-S-backspace
