#+DATE: Time-stamp: <2021-10-03 19:46:41 dieter>
#+bind: org-html-preamble-format (("en" "%d"))
#+OPTIONS: html-link-use-abs-url:nil html-postamble:t html-preamble:t
#+OPTIONS: html-scripts:t html-style:t html5-fancy:nil tex:t
#+HTML_DOCTYPE: xhtml-strict
#+HTML_CONTAINER: div
#+HTML_LINK_HOME: https://github.com/dieter-wilhelm/ansys-mode
#+HTML_LINK_UP: index.html
#+HTML_HEAD:
#+HTML_HEAD_EXTRA:
#+HTML_MATHJAX:
#+INFOJS_OPT:
#+LATEX_HEADER:

#+STARTUP: showall
# #+title: INSTALLATION of APDL-Mode

Copyright (C) 2006 - 2021  H. Dieter Wilhelm, GPL V3

  Please install the [[https://www.gnu.org/software/emacs/][GNU-Emacs]] Editor first, for all functionality
  APDL-Mode requires version 25.1 (released in 2016) but its sources
  can be used with older versions (Emacs-24).  If you are new to this
  editor please check its tutorial in the `Help' menu, or read at
  least the APDL-Mode introduction.

* Melpa Installation
  APDL-Mode is now available on the GNU-Emacs packages archive [[https://melpa.org/][Melpa]]
  for Emacs version 25.1 or newer.

  [[https://melpa.org/#/apdl-mode][file:https://melpa.org/packages/apdl-mode-badge.svg]]
  [[https://stable.melpa.org/#/apdl-mode][file:https://stable.melpa.org/packages/apdl-mode-badge.svg]]

  Please add
  #+begin_src emacs-lisp
    (package-initialize)
    (add-to-list 'package-archives
	  '("melpa" . "https://melpa.org/packages/") t)
  #+end_src

  to your initialisation file.  Activate this code (for example by
  restarting Emacs), then type `M-x install-package', answer the
  prompt with "apdl-mode" and conclude this command with <RET>.

  (You might also install it with GNU-Emacs' package interface `M-x
  list-packages', find `apdl-mode', mark it with `i' and install it
  with `x'.)

   If you prefer the stable package archive instead of the development
   versions, exchange above package source with
   #+begin_src emacs-lisp
      (add-to-list 'package-archives
      '("melpa-stable" . "https://stable.melpa.org/packages/") t)
   #+end_src

* Manual Installation
  If you are behind a corporate firewall and you are not able to
  install APDL-Mode from Emacs' package menu, you can download and
  install its package manually:

  - Download the latest APDL-Mode's tar package from [[https://melpa.org/#/apdl-mode][Melpa]] or - for a
    released package - from the [[https://github.com/dieter-wilhelm/apdl-mode/releases/][Github release page]] under Assets.
  - Install the package within Emacs: Please type `M-x
    package-install-file <RET>' and select your downloaded tar file.

  That's it.

  *Hint:* If you are getting an error message "package.el is not yet
  initialised", you are using Emacs' packaging system for the first
  time.  It is necessary to initialise this machinery once, please
  type: `M-: (package-initialize) <RET>' (it's an 'ALT + :' colon!)
  and then apply `M-x package-install-file <RET>' again.

* Development and Source Code Installation
  Please clone the APDL-Mode git archive in a directory of your
  choice:
  #+begin_src sh
    git clone https://github.com/dieter-wilhelm/apdl-mode.git
  #+end_src
  or download the GitHub ZIP archive and add the following line
  #+begin_src elisp
   (require 'apdl-mode)
  #+end_src
  to your initialisation file (the source directory must be set in the
  `load-path' variable as well).
