#+DATE: Time-stamp: <2021-08-30>
#+bind: org-html-preamble-format (("en" "%d"))
#+OPTIONS: html-link-use-abs-url:nil html-postamble:t html-preamble:t
#+OPTIONS: html-scripts:t html-style:t html5-fancy:nil tex:t
#+HTML_DOCTYPE: xhtml-strict
#+HTML_CONTAINER: div
#+HTML_LINK_HOME: https://github.com/dieter-wilhelm/ansys-mode
#+HTML_LINK_UP: index.html
#+HTML_HEAD:
#+HTML_HEAD_EXTRA:
#+HTML_MATHJAX:
#+INFOJS_OPT:
#+LATEX_HEADER:

#+STARTUP: showall
# #+title: INSTALLATION of APDL-Mode

Copyright (C) 2006 - 2021  H. Dieter Wilhelm, GPL V3

  Please install the [[https://www.gnu.org/software/emacs/][GNU-Emacs]] Editor first, For all functionality
  APDL-Mode needs version 25.1 (from 2016) or newer.  (If you are new
  to this editor please check its tutorial in the `Help' menu, or read
  at least the APDL-Mode introduction.)
* Melpa
   APDL-Mode is now available on the GNU-Emacs packages archive [[https://melpa.org/][Melpa]].

   [[https://melpa.org/#/apdl-mode][file:https://melpa.org/packages/apdl-mode-badge.svg]]
   [[https://stable.melpa.org/#/apdl-mode][file:https://stable.melpa.org/packages/apdl-mode-badge.svg]]

   Please add
   #+begin_src emacs-lisp
   (add-to-list 'package-archives
	     '("melpa" . "https://melpa.org/packages/") t)
   #+end_src

   to your initialisation file.  Then type: `M-x list-packages', find
   `apdl-mode', mark it with `i' and install it with `x'.

   If you prefer the stable package archive instead of development
   versions, exchange above package source with
   #+begin_src emacs-lisp
      (add-to-list 'package-archives
      '("melpa-stable" . "https://stable.melpa.org/packages/") t)
   #+end_src

* Manual installation
   If you are behind a corporate firewall and you are not able to
   install APDL-Mode from Emacs' package menu, you can download and
   install APDL-Mode manually:

   - Download the latest APDL-Mode's tar package from [[https://melpa.org/#/apdl-mode][Melpa]] or - for a
     released package - from the [[https://github.com/dieter-wilhelm/apdl-mode/releases/tag/20.1.0][Github]] release page.
   - Install the package within Emacs: Please type `M-x
     package-install-file <RET>' and select your downloaded tar file.

   That's it.

   *Hint:* If you are getting an error message "package.el is not yet
   initialized", you are using Emacs' packaging system for the very
   first time.  It is necessary to initialise this machinery once,
   please type: `M-: (package-initialize) <RET>' (it's an 'ALT + :'
   colon!)  and then apply `M-x package-install-file <RET>' again.

* Development and source code installation
   Please clone the APDL-Mode git archive in a directory of your
   choice:
   #+begin_src sh
     git clone https://github.com/dieter-wilhelm/apdl-mode.git
   #+end_src
   or download the Github ZIP archive and add the following line
   #+begin_src elisp
   (require 'apdl-mode)
   #+end_src
   to your initialisation file (the source directory must be set in
   the `load-path' variable as well).
