ALL: xSendReturn xPasteToWin xFocusWindow

xFocusWindow : xFocusWindow.cpp
	g++ $<  -lX11 -L/usr/X11R6/lib -o $@
xSendReturn : xSendReturn.cpp
	g++ $<  -lX11 -L/usr/X11R6/lib -o $@
xPasteToWin : xPasteToWin.cpp
	g++ $<  -lX11 -L/usr/X11R6/lib -o $@
